object Versions {
    const val androidxCoreVersion = "1.12.0"
    const val appcompatVersion = "1.6.1"
    const val materialVersion = "1.10.0"
    const val constraintLayoutVersion = "2.1.4"
    const val jUnitVersion = "4.13.2"
    const val androidxJUnitVersion = "1.1.5"
    const val androidxEspressoVersion = "3.5.1"
    const val mockkVersion = "1.13.8"
    const val lottieVersion = "6.1.0"
    const val daggerVersion = "2.49"
    const val retrofitVersion = "2.9.0"
    const val ciceroneVersion = "7.1"
    const val fragmentVersion = "1.6.2"
    const val lifecycleVersion = "2.6.2"
    const val roomVersion = "2.6.0"
    const val rxJavaVersion = "3.1.8"
    const val rxAndroidVersion = "3.0.2"
    const val moxyVersion = "2.2.2"
    const val javaxInject = "1"
    const val coilVersion = "2.5.0"
    const val swipeRefreshLayoutVersion = "1.1.0"
}